# -*- coding: utf-8 -*-
"""Acronym Maker | 1.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6hakCkWK-CUB6c_z0CTdmviyOIFzoaV

Logic:
*   Input given phrase
*   Look for first letter of each word
*   Capitalize the letter
*   Return & print the acronym
"""

def first_letter_search(phrase):
  first_letter = phrase.upper().split()
  for letters in first_letter:
    print(letters[0], end='')

phrase = input("Enter phrase: ")
first_letter_search(phrase)