# -*- coding: utf-8 -*-
"""Dice Rolling Simulator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MXwZCE1PIZQm040JLxOb9eUAFSFLzPRW

1. Create two dice
2. Assign min (1) value and max (6) value
3. User will initiate rolling of the dice
4. Dice values will be randomly generated for each
5. Print out both values of the dice
"""

import random as rd
import time
die_one = rd.randrange(1,7)
die_two = rd.randrange(1,7)

roll_again = 'y'

while roll_again == 'y':
  print('Rolling dice...')
  time.sleep(2)
  print(f'Die One: {die_one}, Die Two: {die_two}')

  roll_again = input('Roll the dice again? (y/n) ')