# -*- coding: utf-8 -*-
"""Rock Paper Scissors

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtKPtJQaDHUaTkMlvf6fFvm7s6UE5aiZ
"""

# Rules #
# Paper wins over rock
# Rock wins over scissors
# Scissors win over paper

import random
rock = 0
paper = 1
scissors = 2

# 1 beats 0
# 0 beats 2
# 2 beats 1

player_score = 0
cpu_score = 0

def cpu_number_to_word_converter():
  number = random.randint(0,2)
  if number == 0:
    return 'rock'
  elif number == 1:
    return 'paper'
  elif number == 2:
    return 'scissors'

def round_winner(cpu_hand, player_hand):
  if cpu_hand == 'paper' and player_hand == 'rock':
    return "WINNER: CPU"
  elif cpu_hand == 'rock' and player_hand == 'scissors':
    return "WINNER: CPU"
  elif cpu_hand == 'scissors' and player_hand == 'paper':
    return "WINNER: CPU"
  elif cpu_hand == 'rock' and player_hand == 'paper':
    return "WINNER: YOU"
  elif cpu_hand == 'scissors' and player_hand == 'rock':
    return "WINNER: YOU"
  elif cpu_hand == 'paper' and player_hand == 'scissors':
    return "WINNER: YOU"
  else:
    return "TIE"

def score_keeper(match_winner):
  global cpu_score
  global player_score
  if match_winner == 'WINNER: CPU':
    cpu_score += 1
  elif match_winner == 'WINNER: YOU':
    player_score += 1
  return f'CPU: {cpu_score}', f'YOU: {player_score}'

player_hand = input("Your move: ").lower()
cpu_hand = cpu_number_to_word_converter()
match_winner = round_winner(cpu_hand, player_hand)
score_keeper
print(f'CPU MOVE: {cpu_hand}')
print(round_winner(cpu_hand, player_hand))
print(score_keeper(match_winner))